import type { Metadata } from 'next'
import ReactQueryProvider from '../utils/provider/ReactQueryProvider';
import "./globals.css";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html>
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
    
  )
}
